site_name: MkDocs 文档开发教程
theme: readthedocs
#theme: rtd-dropdown

nav:
  - 简介: index.md
  - Mkdocs 入门:
    - 安装 MkDocs: get-started/install-MkDocs.md
    - 创建项目: get-started/create-program.md
    - 发布站点: get-started/deploy.md
  - MkDocs 进阶操作:
    - MkDocs-advanced-operations/theme-configuration.md
    - MkDocs-advanced-operations/files-layout.md
  - 附录:
    - YAML 简介: appendix/YAML 简介.md
    - 在技术文档写作中使用 Git: appendix/Git.md
    - 在技术文档写作中使用 GitHub Desktop: appendix/GitHub Desktop.md
    - Markdown 基础语法: appendix/Markdown.md

markdown_extensions:
  - toc:


    
  
