site_name: MkDocs 文档开发教程
theme: readthedocs
nav:
  - 简介: index.md
  - Mkdocs 入门:
    - 安装 MkDocs: 安装 MkDocs.md
    - 创建你的第一个项目: 创建你的第一个项目.md
    - 发布站点: 将站点发布到网络上.md
  - MkDocs 进阶操作:
    - MkDocs 进阶操作/文档布局.md
    - MkDocs 进阶操作/主题配置.md

    
  
