site_name: MkDocs 文档开发教程
#theme: readthedocs
theme: rtd-dropdown

nav:
  - 简介: index.md
  - Mkdocs 入门:
    - 安装 MkDocs: 安装 MkDocs.md
    - 创建你的第一个项目: 创建你的第一个项目.md
    - 发布站点: 将站点发布到网络上.md
  - MkDocs 进阶操作:
    - MkDocs 进阶操作/主题配置.md
    - MkDocs 进阶操作/文档布局.md
  - 附录:
    - 附录/YAML 简介.md
    - 附录/Git.md
    - 附录/GitHub for Desktop.md
    - 附录/Markdown 语法.md


    
  
