site_name: MkDocs 文档开发教程
theme: 
  name: rtd-dropdown
  navigation_depth: 1
  collapse_navigation: false
  titles_only: true

nav:
  - 简介: index.md
  - Mkdocs 快速入门:
    - 安装 MkDocs: get-started/install-MkDocs.md
    - 创建项目: get-started/create-program.md
    - 发布站点: get-started/deploy.md
  - MkDocs 进阶操作:
    - 主题配置: MkDocs-advanced-operations/theme-configuration.md
    - 文档布局: MkDocs-advanced-operations/files-layout.md
  - 附录:
    - 在技术文档写作中使用 Git: appendix/Git.md
    - 在技术文档写作中使用 GitHub Desktop: appendix/GitHub Desktop.md
    - Markdown 基础语法: appendix/Markdown.md

markdown_extensions:
  - toc:




    
  
